<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>1701;1702;IDE0290</NoWarn>
    <InformationalVersion>0.0.1 Demo</InformationalVersion>
    <AssemblyVersion>0.0.1.0</AssemblyVersion>
    <Configurations>Debug;Release;Snapshots</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DefineConstants>$(DefineConstants);INCLUDE_STATE_MACHINE_ATTRIBUTES</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Snapshots'">
    <DefineConstants>$(DefineConstants);INCLUDE_STATE_MACHINE_ATTRIBUTES</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Twia.StateMachine\Twia.StateMachine.csproj" />
    <ProjectReference Include="..\Twia.StateMachine.CodeGenerator\Twia.StateMachine.CodeGenerator.csproj" PrivateAssets="all" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
  </ItemGroup>

</Project>
