<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
    <LangVersion>default</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>1701;1702;IDE0290</NoWarn>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Configurations>Debug;Release;Snapshots</Configurations>
  </PropertyGroup>

  <PropertyGroup>
    <Title>TWIA State Machine Generator</Title>
    <Authors>TWIA / Daniël te Winkel</Authors>
    <Product>$(SolutionName)</Product>
    <Description>Attributes and code generator needed to generate a fully functional state machine in C#.</Description>
    <PackageProjectUrl>https://github.com/dtewinkel/Twia.StateMachine</PackageProjectUrl>
    <VersionPrefix>0.0.1</VersionPrefix>
    <VersionSuffix>local-build</VersionSuffix>
    <RepositoryUrl>https://github.com/dtewinkel/Twia.StateMachine.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>state machine trigger transition code generator generation</PackageTags>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Copyright>Copyright TWIA 2025-2026</Copyright>
    <ApplicationIcon>images/twia-logo.ico</ApplicationIcon>
    <PackageIcon>twia-logo-128.png</PackageIcon>
    <PackageReleaseNotes>
      Edit the release notes in ReleaseNotes.txt.
    </PackageReleaseNotes>
  </PropertyGroup>

  <Target Name="PreparePackageReleaseNotesFromFile" BeforeTargets="GenerateNuspec">
    <PropertyGroup>
      <PackageReleaseNotes>
        $([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/ReleaseNotes.txt"))
      </PackageReleaseNotes>
    </PropertyGroup>
  </Target>

  <ItemGroup>
    <None Include="../Twia.StateMachine.CodeGenerator/bin/$(Configuration)/net8.0/Twia.StateMachine.CodeGenerator.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
    <None Include="images/twia-logo-128.png" Pack="true" PackagePath="/" Visible="true" />
    <None Include="../../LICENSE.md" Pack="true" PackagePath="/" Link="LICENSE.md" />
    <None Include="../../README.md" Pack="true" PackagePath="/" Link="README.md" />
  </ItemGroup>

</Project>
