<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>1701;1702;IDE0290;RS1041</NoWarn>
    <Configurations>Debug;Release;Snapshots</Configurations>
  </PropertyGroup>

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <Deterministic>True</Deterministic>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <DevelopmentDependency>true</DevelopmentDependency>
    <IsRoslynComponent>true</IsRoslynComponent>
    <enforceExtendedAnalyzerRules>enable</enforceExtendedAnalyzerRules>
  </PropertyGroup>

  <PropertyGroup>
    <Title>TWIA State Machine Generator</Title>
    <Authors>TWIA / Daniël te Winkel</Authors>
    <Product>$(SolutionName)</Product>
    <Description>Code generator needed to generate a fully functional state machine in C#.</Description>
    <VersionPrefix>0.0.1</VersionPrefix>
    <VersionSuffix>local-build</VersionSuffix>
    <Copyright>Copyright TWIA 2025-2026</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Generator.Equals" Version="4.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.3.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" PrivateAssets="all" />
  </ItemGroup>

</Project>
