// <auto-generated/>
// Generated by Twia.StateMachine.CodeGenerator version {{Version}} at {{Time}} UTC.
#nullable enable

namespace Twia.StateMachine.CodeGenerator.UnitTests;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Twia.StateMachine.CodeGenerator", "{{Version}}")]
internal partial class UnitTestEmptyStateMachine
{
    /// <summary>
    /// Enumeration of the states that the state machine can be in.
    /// </summary>
    /// <remarks>
    /// The names of the members of the <see cref="UnitTestEmptyStateMachine.State" /> enum are the names of the state methods of the <see cref="UnitTestEmptyStateMachine" /> class.
    /// </remarks>
    public enum State
    {
        Off = 1,
        On
    }

    private enum __{{GeneratedId}}_Trigger
    {
        __{{GeneratedId}}_Undefined = 0,
        ButtonPressed,
        __{{GeneratedId}}_Entry
    }

    private const UnitTestEmptyStateMachine.State __{{GeneratedId}}_StateUndefined = (UnitTestEmptyStateMachine.State)0;

    private UnitTestEmptyStateMachine.State __{{GeneratedId}}_CurrentState = __{{GeneratedId}}_StateUndefined;

    private __{{GeneratedId}}_Trigger __{{GeneratedId}}_LastTrigger = __{{GeneratedId}}_Trigger.__{{GeneratedId}}_Undefined;

    /// <inheritdoc />
    public event global::System.EventHandler<global::Twia.StateMachine.StateChangedEventArgs<UnitTestEmptyStateMachine.State>>? OnStateChanged;

    /// <summary>
    /// Initialize the state machine before it is used.
    /// </summary>
    /// <remarks>
    /// The state machine must be initialize once (and only once) before any of the other generated methods and properties can be used.
    /// </remarks>
    /// <exception cref="global::System.InvalidOperationException">
    /// InitializeStateMachine() can only be called one in the life of a state machine
    /// </exception>
    public void InitializeStateMachine()
    {
        if (__{{GeneratedId}}_CurrentState != __{{GeneratedId}}_StateUndefined)
        {
            throw new global::System.InvalidOperationException("'InitializeStateMachine()' can only be called once in the lifecycle of an instance.");
        }

        // Move to initial state 'Off'.
        __{{GeneratedId}}_EnterState(UnitTestEmptyStateMachine.State.Off, "Initial");
    }

    public partial void ButtonPressed()
    {
        __{{GeneratedId}}_AssertIsInitialized();

        __{{GeneratedId}}_InvokeTrigger(__{{GeneratedId}}_Trigger.ButtonPressed);
    }

    private void __{{GeneratedId}}_AssertIsInitialized()
    {
        if (__{{GeneratedId}}_CurrentState == __{{GeneratedId}}_StateUndefined)
        {
            throw new global::System.InvalidOperationException("The state machine is not initialized yet. Call 'InitializeStateMachine()' on the UnitTestEmptyStateMachine instance before using it.");
        }
    }

    private void __{{GeneratedId}}_InvokeTrigger(__{{GeneratedId}}_Trigger trigger)
    {
        __{{GeneratedId}}_LastTrigger = trigger;

        switch (__{{GeneratedId}}_CurrentState)
        {
            case UnitTestEmptyStateMachine.State.Off:
                Off();
                break;

            case UnitTestEmptyStateMachine.State.On:
                On();
                break;
        }
    }

    private void __{{GeneratedId}}_EnterState(UnitTestEmptyStateMachine.State state, string reason)
    {
        __{{GeneratedId}}_StateChanged(__{{GeneratedId}}_CurrentState, state, reason);

        __{{GeneratedId}}_CurrentState = state;
        __{{GeneratedId}}_InvokeTrigger(__{{GeneratedId}}_Trigger.__{{GeneratedId}}_Entry);
    }

    internal partial void Off()
    {
        switch (__{{GeneratedId}}_LastTrigger)
        {
            case __{{GeneratedId}}_Trigger.ButtonPressed:
                if (CanTransition == true)
                {
                    CanTransition = false;

                    __{{GeneratedId}}_EnterState(UnitTestEmptyStateMachine.State.On, "Trigger: ButtonPressed");
                }
                break;
        }
    }

    partial void On()
    {
    }

    private void __{{GeneratedId}}_StateChanged(
        UnitTestEmptyStateMachine.State fromState,
        UnitTestEmptyStateMachine.State toState,
        string reason
        )
    {
        var nullableFromState = fromState == __{{GeneratedId}}_StateUndefined ? (UnitTestEmptyStateMachine.State?)null : fromState;
        OnStateChanged?.Invoke(this,
            new global::Twia.StateMachine.StateChangedEventArgs<UnitTestEmptyStateMachine.State>(nullableFromState, toState, reason)
        );
    }
}
