// <auto-generated/>
// Generated by Twia.StateMachine.CodeGenerator version {{Version}} at {{Time}} UTC.
#nullable enable

namespace Twia.StateMachine.CodeGenerator.UnitTests;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Twia.StateMachine.CodeGenerator", "{{Version}}")]
internal partial class UnitTestEmptyAsyncStateMachine
{
    /// <summary>
    /// Enumeration of the states that the state machine can be in.
    /// </summary>
    /// <remarks>
    /// The names of the members of the <see cref="UnitTestEmptyAsyncStateMachine.State" /> enum are the names of the state methods of the <see cref="UnitTestEmptyAsyncStateMachine" /> class.
    /// </remarks>
    public enum State
    {
        Off = 1,
        On
    }

    private enum __{{GeneratedId}}_Trigger
    {
        __{{GeneratedId}}_Undefined = 0,
        ButtonPressed,
        __{{GeneratedId}}_Entry,
        __{{GeneratedId}}_OnAfter1
    }

    private const UnitTestEmptyAsyncStateMachine.State __{{GeneratedId}}_StateUndefined = (UnitTestEmptyAsyncStateMachine.State)0;

    private UnitTestEmptyAsyncStateMachine.State __{{GeneratedId}}_CurrentState = __{{GeneratedId}}_StateUndefined;

    private __{{GeneratedId}}_Trigger __{{GeneratedId}}_LastTrigger = __{{GeneratedId}}_Trigger.__{{GeneratedId}}_Undefined;

    private global::System.Collections.Generic.List<global::System.Threading.Timer> __{{GeneratedId}}_Timers = [];

/// <summary>
/// Readonly property to get the current state the state machine is in.
/// </summary>
/// <value>
/// The current state of the state machine.
/// </value>
/// <exception cref="global::System.InvalidOperationException">
/// the state is not initialized yet
/// </exception>
public State CurrentState
    {
        get
        {
            __{{GeneratedId}}_AssertIsInitialized();

            return __{{GeneratedId}}_CurrentState;
        }
    }

    /// <summary>
    /// Initialize the state machine before it is used.
    /// </summary>
    /// <remarks>
    /// The state machine must be initialize once (and only once) before any of the other generated methods and properties can be used.
    /// </remarks>
    /// <exception cref="global::System.InvalidOperationException">
    /// InitializeStateMachine() can only be called one in the life of a state machine
    /// </exception>
    public async global::System.Threading.Tasks.Task InitializeStateMachineAsync(global::System.Threading.CancellationToken cancellationToken = default)
    {
        if (__{{GeneratedId}}_CurrentState != __{{GeneratedId}}_StateUndefined)
        {
            throw new global::System.InvalidOperationException("'InitializeStateMachine()' can only be called once in the lifecycle of an instance.");
        }

        // Move to initial state 'Off'.
        await __{{GeneratedId}}_EnterStateAsync(UnitTestEmptyAsyncStateMachine.State.Off, "Initial", cancellationToken);
    }

    public partial async global::System.Threading.Tasks.Task ButtonPressed()
    {
        __{{GeneratedId}}_AssertIsInitialized();

        await __{{GeneratedId}}_InvokeTriggerAsync(__{{GeneratedId}}_Trigger.ButtonPressed);
    }

    private void __{{GeneratedId}}_AssertIsInitialized()
    {
        if (__{{GeneratedId}}_CurrentState == __{{GeneratedId}}_StateUndefined)
        {
            throw new global::System.InvalidOperationException("The state machine is not initialized yet. Call 'InitializeStateMachine()' on the UnitTestEmptyAsyncStateMachine instance before using it.");
        }
    }

    private async global::System.Threading.Tasks.Task __{{GeneratedId}}_InvokeTriggerAsync(__{{GeneratedId}}_Trigger trigger, global::System.Threading.CancellationToken cancellationToken = default)
    {
        __{{GeneratedId}}_LastTrigger = trigger;

        switch (__{{GeneratedId}}_CurrentState)
        {
            case UnitTestEmptyAsyncStateMachine.State.Off:
                await Off(cancellationToken);
                break;

            case UnitTestEmptyAsyncStateMachine.State.On:
                await On();
                break;
        }
    }

    private async global::System.Threading.Tasks.Task __{{GeneratedId}}_EnterStateAsync(UnitTestEmptyAsyncStateMachine.State state, string reason, global::System.Threading.CancellationToken cancellationToken = default)
    {
        __{{GeneratedId}}_CurrentState = state;
        await __{{GeneratedId}}_InvokeTriggerAsync(__{{GeneratedId}}_Trigger.__{{GeneratedId}}_Entry, cancellationToken);
    }

    internal partial global::System.Threading.Tasks.Task Off(global::System.Threading.CancellationToken ct)
    {
        return global::System.Threading.Tasks.Task.CompletedTask;
    }

    partial global::System.Threading.Tasks.Task On()
    {
        return global::System.Threading.Tasks.Task.CompletedTask;
    }

}
