// <auto-generated/>
// Generated by Twia.StateMachine.CodeGenerator version {{Version}} at {{Time}} UTC.
#nullable enable

namespace Twia.StateMachine.CodeGenerator.UnitTests;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Twia.StateMachine.CodeGenerator", "{{Version}}")]
internal partial class UnitTestStateMachine
{
    /// <summary>
    /// Enumeration of the states that the state machine can be in.
    /// </summary>
    /// <remarks>
    /// The names of the members of the <see cref="UnitTestStateMachine.State" /> enum are the names of the state methods of the <see cref="UnitTestStateMachine" /> class.
    /// </remarks>
    public enum State
    {
        Off = 1,
        On
    }

    private enum __{{GeneratedId}}_Trigger
    {
        __{{GeneratedId}}_Undefined = 0,
        ButtonPressed,
        __{{GeneratedId}}_Entry
    }

    private const UnitTestStateMachine.State __{{GeneratedId}}_StateUndefined = (UnitTestStateMachine.State)0;

    private UnitTestStateMachine.State __{{GeneratedId}}_CurrentState = __{{GeneratedId}}_StateUndefined;

    private __{{GeneratedId}}_Trigger __{{GeneratedId}}_LastTrigger = __{{GeneratedId}}_Trigger.__{{GeneratedId}}_Undefined;

    /// <summary>
    /// Readonly property to get the current state the state machine is in.
    /// </summary>
    /// <value>
    /// The current state of the state machine.
    /// </value>
    /// <exception cref="global::System.InvalidOperationException">
    /// the state is not initialized yet
    /// </exception>
    public State CurrentState
    {
        get
        {
            __{{GeneratedId}}_AssertIsInitialized();

            return __{{GeneratedId}}_CurrentState;
        }
    }

    /// <summary>
    /// Initialize the state machine before it is used.
    /// </summary>
    /// <remarks>
    /// The state machine must be initialize once (and only once) before any of the other generated methods and properties can be used.
    /// </remarks>
    /// <exception cref="global::System.InvalidOperationException">
    /// InitializeStateMachine() can only be called one in the life of a state machine
    /// </exception>
    public void InitializeStateMachine()
    {
        if (__{{GeneratedId}}_CurrentState != __{{GeneratedId}}_StateUndefined)
        {
            throw new global::System.InvalidOperationException("'InitializeStateMachine()' can only be called once in the lifecycle of an instance.");
        }

        // Move to initial state 'Off'.
        __{{GeneratedId}}_EnterState(UnitTestStateMachine.State.Off, "Initial");
    }

    public partial void ButtonPressed()
    {
        __{{GeneratedId}}_AssertIsInitialized();

        __{{GeneratedId}}_InvokeTrigger(__{{GeneratedId}}_Trigger.ButtonPressed);
    }

    private void __{{GeneratedId}}_AssertIsInitialized()
    {
        if (__{{GeneratedId}}_CurrentState == __{{GeneratedId}}_StateUndefined)
        {
            throw new global::System.InvalidOperationException("The state machine is not initialized yet. Call 'InitializeStateMachine()' on the UnitTestStateMachine instance before using it.");
        }
    }

    private void __{{GeneratedId}}_InvokeTrigger(__{{GeneratedId}}_Trigger trigger)
    {
        __{{GeneratedId}}_LastTrigger = trigger;

        switch (__{{GeneratedId}}_CurrentState)
        {
            case UnitTestStateMachine.State.Off:
                Off();
                break;

            case UnitTestStateMachine.State.On:
                On();
                break;
        }
    }

    private void __{{GeneratedId}}_EnterState(UnitTestStateMachine.State state, string reason)
    {
        __{{GeneratedId}}_CurrentState = state;
        __{{GeneratedId}}_InvokeTrigger(__{{GeneratedId}}_Trigger.__{{GeneratedId}}_Entry);
    }

    internal partial void Off()
    {
        switch (__{{GeneratedId}}_LastTrigger)
        {
            case __{{GeneratedId}}_Trigger.ButtonPressed:
                if (_offCount < 100)
                {
                    _offCount++;

                    __{{GeneratedId}}_EnterState(UnitTestStateMachine.State.On, "Trigger: ButtonPressed");
                }
                break;
        }
    }

    partial void On()
    {
        switch (__{{GeneratedId}}_LastTrigger)
        {
            case __{{GeneratedId}}_Trigger.__{{GeneratedId}}_Entry:
                _onCount++;
                break;

            case __{{GeneratedId}}_Trigger.ButtonPressed:
                if (_offCount < 100)
                {
                    _offCount++;

                    __{{GeneratedId}}_EnterState(UnitTestStateMachine.State.On, "Trigger: ButtonPressed");
                }
                break;
        }
    }

}
