using DiffPlex.DiffBuilder;
using DiffPlex.DiffBuilder.Model;
using HandlebarsDotNet;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;

namespace Twia.StateMachine.CodeGenerator.UnitTests.Verifiers;

public interface ISourceGeneratorVerificationPreparer
{
    string Prepare(string sourceText, string actualGeneratedSource, IVerifier verifier);
}

public partial class ReplaceRandomPartsPreparer : ISourceGeneratorVerificationPreparer
{
    [GeneratedRegex(@"// Generated by Twia\.StateMachine\.CodeGenerator version (?<version>[^\s]+) at (?<time>[0-9-]{10} [0-9:]{7,8}) UTC\.", RegexOptions.ExplicitCapture)]
    private static partial Regex VersionAndGenerationTimeRegex();

    [GeneratedRegex(@"private (\w+\.)?(__[\w_]+?_[0-9a-fA-F]{8}_)?State __(?<randomId>[\w_]+?_[0-9a-fA-F]{8})_CurrentState = ", RegexOptions.ExplicitCapture)]
    private static partial Regex RandomIdRegex();

    public record TemplateData(string Version, string Time, string GeneratedId);

    public string Prepare(string sourceText, string actualGeneratedSource, IVerifier verifier)
    {
        var versioningMatches = VersionAndGenerationTimeRegex().Matches(actualGeneratedSource);
        verifier.True(versioningMatches.Count == 1, "Could not find version of date and time of generation.");

        var randomId = "";
        if (sourceText.Contains("{{GeneratedId}}"))
        {
            var randomIdMatches = RandomIdRegex().Matches(actualGeneratedSource);
            verifier.True(randomIdMatches.Count == 1, "Could not find generated Random ID.");
            randomId = randomIdMatches[0].Groups["randomId"].Value;
        }

        var templateData = new TemplateData(
            versioningMatches[0].Groups["version"].Value,
            versioningMatches[0].Groups["time"].Value,
            randomId);
        var template = Handlebars.Compile(sourceText);
        var preparedSource = template(templateData);
        return preparedSource;
    }
}

internal class IncrementalGeneratorVerifier<TGenerator> : CSharpSourceGeneratorTest<TGenerator, DefaultVerifier>
    where TGenerator : IIncrementalGenerator, new()
{
    private readonly string _generatedSourcesPrefix;
    private readonly string _generatedSourcesSuffix;
    private readonly CompilerDiagnostics _compilerDiagnostics;
    private readonly List<ISourceGeneratorVerificationPreparer> _verificationPreparers = [new ReplaceRandomPartsPreparer()];
    private readonly List<Document> _generatorGeneratedSources = [];

    public IncrementalGeneratorVerifier(Type testClassType) : this(
        testClassType.GetNamespacePrefix(),
        "_StateMachine.g.cs",
        // Enable all diagnostics by default, so we can verify that the generator does not produce any unexpected diagnostics.
        CompilerDiagnostics.All)
    {
    }

    public IncrementalGeneratorVerifier(string generatedSourcesPrefix, string generatedSourcesSuffix, CompilerDiagnostics compilerDiagnostics)
    {
        _generatedSourcesPrefix = generatedSourcesPrefix;
        _generatedSourcesSuffix = generatedSourcesSuffix;
        _compilerDiagnostics = compilerDiagnostics;
#if NET10_0
        const string majorMinor = "10.0";
#endif
#if NET9_0
        const string majorMinor = "9.0";
#endif
#if NET8_0
        const string majorMinor = "8.0";
#endif
        TestState.ReferenceAssemblies = new ReferenceAssemblies(
            $"net{majorMinor}",
            new PackageIdentity(
                "Microsoft.NETCore.App.Ref",
                $"{majorMinor}.0"),
            Path.Combine("ref", $"net{majorMinor}"));
    }

    public void AddAdditionalFileReferences(params IEnumerable<string> filePaths)
    {
        foreach (var filePath in filePaths)
        {
            TestState.AdditionalReferences.Add(MetadataReference.CreateFromFile(filePath));
        }
    }

    public string? OutputFile { get; set; }

    public async Task VerifyGeneratorAsync(string[] sources, DiagnosticResult[] diagnostics,
        (string filename, string content)[] generatedSources, CancellationToken cancellationToken)
    {
        TestState.Sources.Clear();
        foreach (var sourceText in sources)
        {
            TestState.Sources.Add(sourceText);
        }

        TestState.GeneratedSources.Clear();
        foreach (var (filename, content) in generatedSources)
        {
            var prefix = filename.StartsWith('*') ? _generatedSourcesPrefix : "";
            var suffix = filename.EndsWith('*') ? _generatedSourcesSuffix : "";
            var fullFilename = $"{prefix}{filename.Trim('*')}{suffix}";
            TestState.GeneratedSources.Add((typeof(TGenerator), fullFilename, content));
        }

        CompilerDiagnostics = _compilerDiagnostics;

        ExpectedDiagnostics.Clear();
        ExpectedDiagnostics.AddRange(diagnostics);

        TestBehaviors = TestBehaviors.SkipGeneratedSourcesCheck;
        await RunAsync(cancellationToken);

        var newSourcesCount = _generatorGeneratedSources.Count;
        var expectedGeneratedSourcesCount = TestState.GeneratedSources.Count;
        Verify.Equal(newSourcesCount, expectedGeneratedSourcesCount, $"The number of generated sources, {newSourcesCount},  does not match the expected count of {expectedGeneratedSourcesCount}");
        if (expectedGeneratedSourcesCount == 1)
        {
            Verify.Equal(newSourcesCount, 1, $"We only expect 1 generated source, not {newSourcesCount}");

            var (_, content) = TestState.GeneratedSources[0];
            var actualGeneratedSource =
                (await _generatorGeneratedSources[0].GetTextAsync(cancellationToken)).ToString();
            if (OutputFile is not null && !string.IsNullOrWhiteSpace(actualGeneratedSource))
            {
                await File.WriteAllTextAsync(OutputFile, actualGeneratedSource, new UTF8Encoding(true),
                    cancellationToken);
            }

            var preparedDocument = content.ToString();
            foreach (var verificationPreparer in _verificationPreparers)
            {
                preparedDocument = verificationPreparer.Prepare(preparedDocument, actualGeneratedSource, Verify);
            }

            var diffText = new StringBuilder();
            var diff = InlineDiffBuilder.Diff(preparedDocument, actualGeneratedSource, ignoreWhiteSpace: false);
            if (diff.HasDifferences)
            {
                diffText.AppendLine("generated source files and expected source files should be the same: ");
                diffText.AppendLine();
                foreach (var line in diff.Lines)
                {

                    var prefix = line.Type switch
                    {
                        ChangeType.Inserted => "+", 
                        ChangeType.Deleted => "-",
                        ChangeType.Modified => "*",
                        ChangeType.Imaginary => "?",
                        _ => " "
                    };

                    diffText.AppendLine($"{line.Position,-4} {prefix}  {line.Text}");
                }
                Verify.Fail(diffText.ToString());
            }
        }
    }

    protected override async Task<(Compilation compilation, ImmutableArray<Diagnostic> generatorDiagnostics)> GetProjectCompilationAsync(Project project, IVerifier verifier, CancellationToken cancellationToken)
    {
        // Call the private method in IncrementalGeneratorVerifier via reflection, so we can access the project to get the generated sources after source generation.
        var (finalProject, generatorDiagnostics) = await InvokeApplySourceGeneratorsAsync(project, verifier, cancellationToken);

        _generatorGeneratedSources.AddRange(finalProject.Documents.Skip(TestState.Sources.Count));

        return ((await finalProject.GetCompilationAsync(cancellationToken).ConfigureAwait(false))!, generatorDiagnostics);
    }

    private async Task<(Project compilationProject, ImmutableArray<Diagnostic> generatorDiagnostics)> InvokeApplySourceGeneratorsAsync(
        Project project,
        IVerifier verifier,
        CancellationToken cancellationToken)
    {
        var method = GetType().GetMethod("ApplySourceGeneratorsAsync", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                     ?? throw new InvalidOperationException("ApplySourceGeneratorsAsync method not found on verifier instance.");

        // Invoke the method. It returns Task<(Project, ImmutableArray<Diagnostic>)>
        var invocation = method.Invoke(this, [GetSourceGenerators().ToImmutableArray(), project, verifier, cancellationToken])
                   ?? throw new InvalidOperationException("Invocation returned null.");

        // Await the returned Task (Task or Task<T>)
        var task = (Task)invocation;
        await task.ConfigureAwait(false);

        // Get Result property from Task<T>
        var resultProp = invocation.GetType().GetProperty("Result", BindingFlags.Instance | BindingFlags.Public)
                         ?? throw new InvalidOperationException("Returned task does not have a Result property.");

        var result = resultProp.GetValue(invocation);
        return ((Project, ImmutableArray<Diagnostic>))result!;
    }

    protected override ParseOptions CreateParseOptions()
    {
        return ((CSharpParseOptions)base.CreateParseOptions()).WithLanguageVersion(LanguageVersion.Default);
    }
}
