using System.CodeDom.Compiler;
using System.Reflection;
using Twia.StateMachine.CodeGenerator.Declarations;

namespace Twia.StateMachine.CodeGenerator.Builders.Async;

public class ClassCommonBuilder
{
    private static readonly string _randomIdInPrefix = Guid.NewGuid().ToString("N")[..8];

    private readonly string _generatorVersion;
    private readonly string _generatorName;

    private int _nestingLevel = 0;

    private readonly CSharpDocumentWriter _document;
    private readonly StateMachineDeclaration _declaration;

    private readonly string _privatePrefix;
    
    public string StateMachineName { get; }

    public string FullStateMachineTypeName { get; private set; } = "";

    public ClassCommonBuilder(CSharpDocumentWriter document, StateMachineDeclaration declaration)
    {
        _document = document;
        _declaration = declaration;
        StateMachineName = declaration.Name;

        var assembly = typeof(StateMachineIncrementalCodeGenerator).Assembly;
        _generatorName = assembly.GetName().Name ?? "Unknown";
        _generatorVersion = assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion ?? "Unknown";

        _privatePrefix = $"__{StateMachineName}_{_randomIdInPrefix}_";
    }

    public string ToPrivateName(string name) => $"{_privatePrefix}{name}";

    public void StartClass()
    {
        var typeNameParts = new List<string>();

        AddHeader();
        AddNamespace(typeNameParts);

        AddParentClass(_declaration.Parent, typeNameParts);
        _document.WriteLine($"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"{_generatorName}\", \"{_generatorVersion}\")]");
        AddClassStart(_declaration, typeNameParts);
         
        FullStateMachineTypeName = string.Join(".", typeNameParts);
    }

    private void AddHeader()
    {
        var timestamp = DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss");

        _document.WriteLine("// <auto-generated/>");
        _document.WriteLine($"// Generated by {_generatorName} version {_generatorVersion} at {timestamp} UTC.");
        _document.WriteLine("#nullable enable");
        _document.WriteLineNoTabs();
    }

    private void AddNamespace(List<string> typeNameParts)
    {
        var namespaceName = _declaration.FullNamespaceName;
        if (namespaceName is null)
        {
            return;
        }

        _document.WriteLine($"namespace {namespaceName};");
        _document.WriteLineNoTabs();
        typeNameParts.Add(namespaceName);
    }

    private void AddParentClass(ParentDeclaration? parent, List<string> typeNameParts)
    {
        if (parent is not ContainingClassDeclaration containingClass)
        {
            return;
        }

        if (containingClass.Parent is not null)
        {
            AddParentClass(containingClass.Parent, typeNameParts);
        }

        AddClassStart(containingClass.ClassDeclaration, typeNameParts);
    }

    private void AddClassStart(ClassDeclaration declaration, List<string> typeNameParts)
    {
        _document.WriteLine($"{declaration.Modifiers} class {declaration.Name}");
        _document.WriteLineBlockOpen();

        typeNameParts.Add(declaration.Name);
        _nestingLevel++;
    }

    public void EndClass()
    {
        while (_nestingLevel > 0)
        {
            _document.WriteLineBlockClose();
            _nestingLevel--;
        }
    }

    public static string ToMethodDeclaration(MethodReturnType returnType, string methodName, string? cancellationTokenName, bool addAsyncIfAsync = true)
    {
        var isAsync = returnType == MethodReturnType.AsyncTask;
        var returnTypeType = returnType switch
        {
            MethodReturnType.AsyncTask => CommonTypeNames.Task,
            MethodReturnType.Task => CommonTypeNames.Task,
            MethodReturnType.Void => CommonTypeNames.Void,
            MethodReturnType.Other => throw new InvalidOperationException($"Return type {returnType} is not supported."),
            MethodReturnType.Mixed => throw new InvalidOperationException($"Return type {returnType} is not supported."),
            _ => throw new ArgumentOutOfRangeException(nameof(returnType), returnType, null)
        };
        var asyncPrefix = string.Empty;
        var methodNamePostfix = string.Empty;
        var cancellationParameter = string.Empty;
        if (isAsync || returnTypeType == CommonTypeNames.Task)
        {
            asyncPrefix = "async ";
            if (addAsyncIfAsync)
            {
                methodNamePostfix = "Async";
            }

            cancellationParameter = $"{CommonTypeNames.CancellationToken} cancellationToken = default";
        }

        return $"{asyncPrefix}{returnTypeType} {methodName}{methodNamePostfix}({cancellationParameter})";
    }

    public static string ToMethodCall(MethodReturnType returnType, string methodName, string? parameters)
    {
        var asyncPrefix = string.Empty;
        var methodNamePostfix = string.Empty;
        if (returnType is MethodReturnType.Task or MethodReturnType.AsyncTask)
        {
            asyncPrefix = "await ";
            methodNamePostfix = "Async";
        }

        return $"{asyncPrefix}{methodName}{methodNamePostfix}({parameters ?? ""});";
    }
}