using System.CodeDom.Compiler;
using System.Reflection;
using Twia.StateMachine.CodeGenerator.Declarations;

namespace Twia.StateMachine.CodeGenerator.Builders.Async;

public class ClassCommonBuilder
{
    private static readonly string _randomIdInPrefix = Guid.NewGuid().ToString("N")[..8];

    private readonly string _generatorVersion;
    private readonly string _generatorName;

    private int _nestingLevel = 0;

    private readonly IndentedTextWriter _document;
    private readonly StateMachineDeclaration _declaration;

    private readonly string _privatePrefix;
    
    public string StateMachineName { get; }

    public string FullStateMachineTypeName { get; private set; } = "";

    public ClassCommonBuilder(IndentedTextWriter document, StateMachineDeclaration declaration)
    {
        _document = document;
        _declaration = declaration;
        StateMachineName = declaration.Name;

        var assembly = typeof(StateMachineIncrementalCodeGenerator).Assembly;
        _generatorName = assembly.GetName().Name ?? "Unknown";
        _generatorVersion = assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion ?? "Unknown";

        _privatePrefix = $"__{StateMachineName}_{_randomIdInPrefix}_";
    }

    public string ToPrivateName(string name) => $"{_privatePrefix}{name}";

    public void StartClass()
    {
        var typeNameParts = new List<string>();

        AddHeader();
        AddNamespace(typeNameParts);

        AddParentClass(_declaration.Parent, typeNameParts);
        _document.WriteLine($"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"{_generatorName}\", \"{_generatorVersion}\")]");
        AddClassStart(_declaration, typeNameParts);
         
        FullStateMachineTypeName = string.Join(".", typeNameParts);
    }

    private void AddHeader()
    {
        var timestamp = DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss");

        _document.WriteLine("// <auto-generated/>");
        _document.WriteLine($"// Generated by {_generatorName} version {_generatorVersion} at {timestamp} UTC.");
        _document.WriteLine("#nullable enable");
        _document.WriteLineNoTabs();
    }

    private void AddNamespace(List<string> typeNameParts)
    {
        var namespaceName = _declaration.FullNamespaceName;
        if (namespaceName is null)
        {
            return;
        }

        _document.WriteLine($"namespace {namespaceName};");
        _document.WriteLineNoTabs();
        typeNameParts.Add(namespaceName);
    }

    private void AddParentClass(ParentDeclaration? parent, List<string> typeNameParts)
    {
        if (parent is not ContainingClassDeclaration containingClass)
        {
            return;
        }

        if (containingClass.Parent is not null)
        {
            AddParentClass(containingClass.Parent, typeNameParts);
        }

        AddClassStart(containingClass.ClassDeclaration, typeNameParts);
    }

    private void AddClassStart(ClassDeclaration declaration, List<string> typeNameParts)
    {
        _document.WriteLine($"{declaration.Modifiers} class {declaration.Name}");
        _document.WriteLineBlockOpen();

        typeNameParts.Add(declaration.Name);
        _nestingLevel++;
    }

    public void EndClass()
    {
        while (_nestingLevel > 0)
        {
            _document.WriteLineBlockClose();
            _nestingLevel--;
        }
    }
}