// <auto-generated/>
// Generated by Twia.StateMachine.CodeGenerator version {{Version}} at {{Time}} UTC.
#nullable enable

namespace Twia.StateMachine.CodeGenerator.UnitTests;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Twia.StateMachine.CodeGenerator", "{{Version}}")]
public partial class UnitTestStateMachine
{
    /// <summary>
    /// Enumeration of the states that the state machine can be in.
    /// </summary>
    /// <remarks>
    /// The names of the members of the <see cref="UnitTestStateMachine.State" /> enum are the names of the state methods of the <see cref="UnitTestStateMachine" /> class.
    /// </remarks>
    public enum State
    {
        /// <summary>The state machine is in the 'State1' state.</summary>
        State1 = 1
    }

    private enum __{{GeneratedId}}_Trigger
    {
        __{{GeneratedId}}_Undefined = 0,
        __{{GeneratedId}}_Entry,
        __{{GeneratedId}}_State1After1
    }

    private const UnitTestStateMachine.State __{{GeneratedId}}_StateUndefined = (UnitTestStateMachine.State)0;

    private UnitTestStateMachine.State __{{GeneratedId}}_CurrentState = __{{GeneratedId}}_StateUndefined;

    private bool __{{GeneratedId}}_IsInitialized = false;

    private __{{GeneratedId}}_Trigger __{{GeneratedId}}_LastTrigger = __{{GeneratedId}}_Trigger.__{{GeneratedId}}_Undefined;

    private global::System.Collections.Generic.List<global::System.Threading.Timer> __{{GeneratedId}}_Timers = [];

    /// <summary>
    /// Readonly property to get the current state the state machine is in.
    /// </summary>
    /// <value>
    /// The current state of the state machine.
    /// </value>
    /// <exception cref="global::System.InvalidOperationException">
    /// the state is not initialized yet
    /// </exception>
    public State CurrentState
    {
        get
        {
            __{{GeneratedId}}_AssertIsInitialized();

            return __{{GeneratedId}}_CurrentState;
        }
    }

    /// <summary>
    /// Initialize the state machine before it is used.
    /// </summary>
    /// <remarks>
    /// The state machine must be initialized once (and only once) before any of the other generated methods and properties can be used.
    /// </remarks>
    /// <exception cref="global::System.InvalidOperationException">
    /// InitializeStateMachine() can only be called once in the life of a state machine
    /// </exception>
    public void InitializeStateMachine()
    {
        if (__{{GeneratedId}}_IsInitialized)
        {
            throw new global::System.InvalidOperationException("'InitializeStateMachine()' can only be called once in the lifecycle of a state machine instance.");
        }

        // Move to initial state 'State1'.
        __{{GeneratedId}}_EnterState(UnitTestStateMachine.State.State1, "Initial");

        __{{GeneratedId}}_IsInitialized = true;
    }

    private void __{{GeneratedId}}_AssertIsInitialized()
    {
        if (!__{{GeneratedId}}_IsInitialized)
        {
            throw new global::System.InvalidOperationException("The state machine is not initialized yet. Call 'InitializeStateMachine()' on the UnitTestStateMachine instance before using it.");
        }
    }

    private void __{{GeneratedId}}_InvokeTrigger(__{{GeneratedId}}_Trigger trigger)
    {
        __{{GeneratedId}}_LastTrigger = trigger;

        switch (__{{GeneratedId}}_CurrentState)
        {
            case UnitTestStateMachine.State.State1:
                State1();
                break;
        }
    }

    private void __{{GeneratedId}}_EnterState(UnitTestStateMachine.State state, string reason)
    {
        if (__{{GeneratedId}}_Timers.Count > 0)
        {
            foreach (var timer in __{{GeneratedId}}_Timers)
            {
                timer.Dispose();
            }
            __{{GeneratedId}}_Timers = [];
        }

        __{{GeneratedId}}_CurrentState = state;
        __{{GeneratedId}}_InvokeTrigger(__{{GeneratedId}}_Trigger.__{{GeneratedId}}_Entry);
    }

    private partial void State1()
    {
        switch (__{{GeneratedId}}_LastTrigger)
        {
            case __{{GeneratedId}}_Trigger.__{{GeneratedId}}_Entry:
                __{{GeneratedId}}_StartTimer("00:01:00", null, __{{GeneratedId}}_Trigger.__{{GeneratedId}}_State1After1);
                break;

            case __{{GeneratedId}}_Trigger.__{{GeneratedId}}_State1After1:
                break;
        }
    }

    private void __{{GeneratedId}}_StartTimer(string delay, string? periode, __{{GeneratedId}}_Trigger trigger)
    {
        var delayTimeSpan = global::System.TimeSpan.Parse(delay);
        var periodeTimeSpan = string.IsNullOrWhiteSpace(periode) ? global::System.Threading.Timeout.InfiniteTimeSpan : global::System.TimeSpan.Parse(periode);
        var timer = new global::System.Threading.Timer(__{{GeneratedId}}_TimerCallback, trigger, delayTimeSpan, periodeTimeSpan);
        __{{GeneratedId}}_Timers.Add(timer);
    }

    private void __{{GeneratedId}}_TimerCallback(object? trigger)
    {
        __{{GeneratedId}}_InvokeTrigger((__{{GeneratedId}}_Trigger)trigger!);
    }
}
