// <auto-generated/>
// Generated by Twia.StateMachine.CodeGenerator version {{Version}} at {{Time}} UTC.
#nullable enable

namespace Twia.StateMachine.CodeGenerator.UnitTests;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Twia.StateMachine.CodeGenerator", "{{Version}}")]
internal partial class UnitTestStateMachine
{
    /// <summary>
    /// Enumeration of the states that the state machine can be in.
    /// </summary>
    /// <remarks>
    /// The names of the members of the <see cref="UnitTestStateMachine.State" /> enum are the names of the state methods of the <see cref="UnitTestStateMachine" /> class.
    /// </remarks>
    public enum State
    {
        /// <summary>The state machine is in the 'Off' state.</summary>
        Off = 1,
        /// <summary>The state machine is in the 'On' state.</summary>
        On
    }

    private enum __{{GeneratedId}}_Trigger
    {
        __{{GeneratedId}}_Undefined = 0,
        ButtonPressed,
        __{{GeneratedId}}_Entry
    }

    private const UnitTestStateMachine.State __{{GeneratedId}}_StateUndefined = (UnitTestStateMachine.State)0;

    private UnitTestStateMachine.State __{{GeneratedId}}_CurrentState = __{{GeneratedId}}_StateUndefined;

    private bool __{{GeneratedId}}_IsInitialized = false;

    private __{{GeneratedId}}_Trigger __{{GeneratedId}}_LastTrigger = __{{GeneratedId}}_Trigger.__{{GeneratedId}}_Undefined;

    /// <summary>
    /// Occurs when the state of the state machine changes.
    /// </summary>
    public event global::System.EventHandler<global::Twia.StateMachine.StateChangedEventArgs<UnitTestStateMachine.State>>? OnStateChanged;

    /// <summary>
    /// Readonly property to get the current state the state machine is in.
    /// </summary>
    /// <value>
    /// The current state of the state machine.
    /// </value>
    /// <exception cref="global::System.InvalidOperationException">
    /// the state is not initialized yet
    /// </exception>
    public State CurrentState
    {
        get
        {
            __{{GeneratedId}}_AssertIsInitialized();

            return __{{GeneratedId}}_CurrentState;
        }
    }

    /// <summary>
    /// Initialize the state machine before it is used.
    /// </summary>
    /// <remarks>
    /// The state machine must be initialized once (and only once) before any of the other generated methods and properties can be used.
    /// </remarks>
    /// <exception cref="global::System.InvalidOperationException">
    /// InitializeStateMachine() can only be called once in the life of a state machine
    /// </exception>
    public void InitializeStateMachine()
    {
        if (__{{GeneratedId}}_IsInitialized)
        {
            throw new global::System.InvalidOperationException("'InitializeStateMachine()' can only be called once in the lifecycle of a state machine instance.");
        }

        // Move to initial state 'Off'.
        __{{GeneratedId}}_EnterState(UnitTestStateMachine.State.Off, "Initial");

        __{{GeneratedId}}_IsInitialized = true;
    }

    public partial void ButtonPressed()
    {
        __{{GeneratedId}}_AssertIsInitialized();

        __{{GeneratedId}}_InvokeTrigger(__{{GeneratedId}}_Trigger.ButtonPressed);
    }

    private void __{{GeneratedId}}_AssertIsInitialized()
    {
        if (!__{{GeneratedId}}_IsInitialized)
        {
            throw new global::System.InvalidOperationException("The state machine is not initialized yet. Call 'InitializeStateMachine()' on the UnitTestStateMachine instance before using it.");
        }
    }

    private void __{{GeneratedId}}_InvokeTrigger(__{{GeneratedId}}_Trigger trigger)
    {
        __{{GeneratedId}}_LastTrigger = trigger;

        switch (__{{GeneratedId}}_CurrentState)
        {
            case UnitTestStateMachine.State.Off:
                Off();
                break;

            case UnitTestStateMachine.State.On:
                On();
                break;
        }
    }

    private void __{{GeneratedId}}_EnterState(UnitTestStateMachine.State state, string reason)
    {
        __{{GeneratedId}}_StateChanged(__{{GeneratedId}}_CurrentState, state, reason);

        __{{GeneratedId}}_CurrentState = state;
        __{{GeneratedId}}_InvokeTrigger(__{{GeneratedId}}_Trigger.__{{GeneratedId}}_Entry);
    }

    internal partial void Off()
    {
        switch (__{{GeneratedId}}_LastTrigger)
        {
            case __{{GeneratedId}}_Trigger.ButtonPressed:
                if (CanTransition == true)
                {
                    CanTransition = false;

                    __{{GeneratedId}}_EnterState(UnitTestStateMachine.State.On, "Trigger: ButtonPressed");
                }
                break;
        }
    }

    partial void On()
    {
    }

    private void __{{GeneratedId}}_StateChanged(
        UnitTestStateMachine.State fromState,
        UnitTestStateMachine.State toState,
        string reason
        )
    {
        var nullableFromState = fromState == __{{GeneratedId}}_StateUndefined ? (UnitTestStateMachine.State?)null : fromState;
        OnStateChanged?.Invoke(this,
            new global::Twia.StateMachine.StateChangedEventArgs<UnitTestStateMachine.State>(nullableFromState, toState, reason)
        );
    }
}
