// <auto-generated/>
// Generated by Twia.StateMachine.CodeGenerator version {{Version}} at {{Time}} UTC.
#nullable enable

namespace Twia.StateMachine.CodeGenerator.UnitTests;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Twia.StateMachine.CodeGenerator", "{{Version}}")]
internal partial class UnitTestEmptyStateMachine
{
    /// <summary>
    /// Enumeration of the states that the state machine can be in.
    /// </summary>
    /// <remarks>
    /// The names of the members of the <see cref="UnitTestEmptyStateMachine.State" /> enum are the names of the state methods of the <see cref="UnitTestEmptyStateMachine" /> class.
    /// </remarks>
    public enum State
    {
        State1 = 1,
        State2
    }

    private enum __{{GeneratedId}}_Trigger
    {
        __{{GeneratedId}}_Undefined = 0,
        __{{GeneratedId}}_Entry
    }

    private const UnitTestEmptyStateMachine.State __{{GeneratedId}}_StateUndefined = (UnitTestEmptyStateMachine.State)0;

    private UnitTestEmptyStateMachine.State __{{GeneratedId}}_CurrentState = __{{GeneratedId}}_StateUndefined;

    private __{{GeneratedId}}_Trigger __{{GeneratedId}}_LastTrigger = __{{GeneratedId}}_Trigger.__{{GeneratedId}}_Undefined;

    /// <summary>
    /// Readonly property to get the current state the state machine is in.
    /// </summary>
    /// <value>
    /// The current state of the state machine.
    /// </value>
    /// <exception cref="global::System.InvalidOperationException">
    /// the state is not initialized yet
    /// </exception>
    public State CurrentState
    {
        get
        {
            __{{GeneratedId}}_AssertIsInitialized();

            return __{{GeneratedId}}_CurrentState;
        }
    }

    /// <summary>
    /// Initialize the state machine before it is used.
    /// </summary>
    /// <remarks>
    /// The state machine must be initialize once (and only once) before any of the other generated methods and properties can be used.
    /// </remarks>
    /// <exception cref="global::System.InvalidOperationException">
    /// InitializeStateMachine() can only be called one in the life of a state machine
    /// </exception>
    public void InitializeStateMachine()
    {
        if (__{{GeneratedId}}_CurrentState != __{{GeneratedId}}_StateUndefined)
        {
            throw new global::System.InvalidOperationException("'InitializeStateMachine()' can only be called once in the lifecycle of an instance.");
        }

        // Move to initial state 'State1'.
        __{{GeneratedId}}_EnterState(UnitTestEmptyStateMachine.State.State1, "Initial");
    }

    private void __{{GeneratedId}}_AssertIsInitialized()
    {
        if (__{{GeneratedId}}_CurrentState == __{{GeneratedId}}_StateUndefined)
        {
            throw new global::System.InvalidOperationException("The state machine is not initialized yet. Call 'InitializeStateMachine()' on the UnitTestEmptyStateMachine instance before using it.");
        }
    }

    private void __{{GeneratedId}}_InvokeTrigger(__{{GeneratedId}}_Trigger trigger)
    {
        __{{GeneratedId}}_LastTrigger = trigger;

        switch (__{{GeneratedId}}_CurrentState)
        {
            case UnitTestEmptyStateMachine.State.State1:
                State1();
                break;

            case UnitTestEmptyStateMachine.State.State2:
                State2();
                break;
        }
    }

    private void __{{GeneratedId}}_EnterState(UnitTestEmptyStateMachine.State state, string reason)
    {
        __{{GeneratedId}}_CurrentState = state;
        __{{GeneratedId}}_InvokeTrigger(__{{GeneratedId}}_Trigger.__{{GeneratedId}}_Entry);
    }

    public partial void State1()
    {
    }

    public partial void State2()
    {
    }

}
