// <auto-generated/>
// Generated by Twia.StateMachine.CodeGenerator version {{Version}} at {{Time}} UTC.
#nullable enable

namespace Twia.StateMachine.CodeGenerator.UnitTests;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Twia.StateMachine.CodeGenerator", "{{Version}}")]
public partial class UnitTestStateMachine
{
    /// <summary>
    /// Enumeration of the states that the state machine can be in.
    /// </summary>
    /// <remarks>
    /// The names of the members of the <see cref="UnitTestStateMachine.State" /> enum are the names of the state methods of the <see cref="UnitTestStateMachine" /> class.
    /// </remarks>
    public enum State
    {
        /// <summary>The state machine is in the 'State1' state.</summary>
        State1 = 1,
        /// <summary>The state machine is in the 'State2' state.</summary>
        State2
    }

    private enum __{{GeneratedId}}_Trigger
    {
        __{{GeneratedId}}_Undefined = 0,
        __{{GeneratedId}}_Entry
    }

    private const UnitTestStateMachine.State __{{GeneratedId}}_StateUndefined = (UnitTestStateMachine.State)0;

    private UnitTestStateMachine.State __{{GeneratedId}}_CurrentState = __{{GeneratedId}}_StateUndefined;

    private bool __{{GeneratedId}}_IsInitialized = false;

    private __{{GeneratedId}}_Trigger __{{GeneratedId}}_LastTrigger = __{{GeneratedId}}_Trigger.__{{GeneratedId}}_Undefined;

    /// <summary>
    /// Readonly property to get the current state the state machine is in.
    /// </summary>
    /// <value>
    /// The current state of the state machine.
    /// </value>
    /// <exception cref="global::System.InvalidOperationException">
    /// the state is not initialized yet
    /// </exception>
    public State CurrentState
    {
        get
        {
            __{{GeneratedId}}_AssertIsInitialized();

            return __{{GeneratedId}}_CurrentState;
        }
    }

    /// <summary>
    /// Initialize the state machine before it is used.
    /// </summary>
    /// <remarks>
    /// The state machine must be initialized once (and only once) before any of the other generated methods and properties can be used.
    /// </remarks>
    /// <exception cref="global::System.InvalidOperationException">
    /// InitializeStateMachine() can only be called once in the life of a state machine
    /// </exception>
    public void InitializeStateMachine()
    {
        if (__{{GeneratedId}}_IsInitialized)
        {
            throw new global::System.InvalidOperationException("'InitializeStateMachine()' can only be called once in the lifecycle of a state machine instance.");
        }

        // Move to initial state 'State1'.
        __{{GeneratedId}}_EnterState(UnitTestStateMachine.State.State1, "Initial");

        __{{GeneratedId}}_IsInitialized = true;
    }

    private void __{{GeneratedId}}_AssertIsInitialized()
    {
        if (!__{{GeneratedId}}_IsInitialized)
        {
            throw new global::System.InvalidOperationException("The state machine is not initialized yet. Call 'InitializeStateMachine()' on the UnitTestStateMachine instance before using it.");
        }
    }

    private void __{{GeneratedId}}_InvokeTrigger(__{{GeneratedId}}_Trigger trigger)
    {
        __{{GeneratedId}}_LastTrigger = trigger;

        switch (__{{GeneratedId}}_CurrentState)
        {
            case UnitTestStateMachine.State.State1:
                State1();
                break;

            case UnitTestStateMachine.State.State2:
                throw new global::System.InvalidOperationException("The state 'State2' is not usable because it does not have the right signature.");
        }
    }

    private void __{{GeneratedId}}_EnterState(UnitTestStateMachine.State state, string reason)
    {
        __{{GeneratedId}}_CurrentState = state;
        __{{GeneratedId}}_InvokeTrigger(__{{GeneratedId}}_Trigger.__{{GeneratedId}}_Entry);
    }

    private partial void State1()
    {
    }

    private partial bool State2()
    {
        return default(bool);
    }

}
