name: .NET Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Solution: Twia.StateMachine.slnx
      Configuration: Release
    defaults:
      run:
        working-directory: src
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.3.1
        with:
          versionSpec: '6.6.x'
          
      - name: Calculate version (GitVersion)
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4.3.1
        with:
          useConfigFile: false
          overrideConfig: |
            next-version=1.0.0

      - name: Create Tag
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a -f v${{ steps.gitversion.outputs.SemVer }} -m "Tag version v${{ steps.gitversion.outputs.SemVer }}"
          git push origin v${{ steps.gitversion.outputs.SemVer }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore $Solution

      - name: Build
        run: >-
          dotnet build $Solution 
          --configuration $Configuration 
          --no-restore
          -p:Version=${{ steps.gitversion.outputs.SemVer }}
          -p:PackageVersion=${{ steps.gitversion.outputs.SemVer }}
          -p:AssemblyVersion=${{ steps.gitversion.outputs.AssemblySemVer }}
          -p:FileVersion=${{ steps.gitversion.outputs.FileSemVer }}
          -p:InformationalVersion=${{ steps.gitversion.outputs.SemVer }}

      - name: Test
        run: dotnet test --solution $Solution --configuration $Configuration --no-build

      - name: Upload NuGet packages
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: src/Twia.StateMachine.CodeGenerator/bin/Release/*.nupkg
